# Generated by Django 5.1.3 on 2024-11-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='default_address', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='default_phone', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_networks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
