# Generated by Django 4.2 on 2026-01-14 13:58

from django.db import migrations, models
import prilogenie.models


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie', '0002_add_user_to_booking'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', prilogenie.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=10, null=True),
        ),
    ]
