# Generated by Django 4.2 on 2025-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie', '0002_remove_contact_message_contact_address_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='portfolio_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
