# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie', '0003_alter_customuser_managers_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prilogenie.photographer'),
        ),
    ]
